### ISSUE TITLE
Опечатки в тексте Стандарта

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#1]
В ходе чтения проекта Стандарта было обнаружено несколько небольших орфографические и пунктуационных неточностей, которые не влияют на смысловое содержание документа:

1. Раздел 1
> Представлена технология OpenID Connect (OIDC), ориентированная на построение в Интернет крупных открытых инфраструктур аутентификации.

Вероятно, вместо "в Интернет" следует писать "в сети Интернет".

2. Подраздел 4.2
> Уровень гарантий определяет степень увереннности в соблюдении процедур и правил, за которые отвечает блок.

Вместо "увереннности" следует писать "уверенности". 

3. Подраздел 4.4
> Кроме этого, сертификаты могут использоваться для создания защишенных соединений между сторонами, например, соединений протокола TLS, установленного в СТБ 34.101.65.

Вместо "защишенных" следует писать "защищенных". 

4. Пункт 6.1.2 (Требование ВТ.5)
> КП не должна хранить подсказки, которые помогают пользователю вспомнить забытый статического пароль.

Вместо "статического" следует писать "статический". 

5. Подраздел 8.1
> Имена и значения параметров кодирутся в формате "application/json", определенном в [3].

Вместо "кодирутся" следует писать "кодируются". 

6. Приложение В.1.3
> Предпочительные уровни гарантий аутентификации могут запрашиваться также через параметр claims (см. В.1.4, Г.4.4).

Вместо "Предпочительные" следует писать "Предпочтительные". 

7. Приложение В.1.15
> Например, значение 300 означает, что БД действует в течении пяти минут с момента формирования ответа.

Согласно [правилу](https://newslab.ru/article/141775) вместо "в течении" следует писать "в течение". 

8. Приложение В.1.26
> Передача по ссылке может быть удобнее, если объект имеет большойц размер.

Вместо "большойц" следует писать "большой". 

9. Приложение В.1.29
> Область действия должна содержать лексему "openid", указывающее на использование технологии OIDC.

Вместо "указывающее" следует писать "указывающую". 

10. Приложение В.1.29
> Область действия может содержать дополнительные лексемы, которые определяюn запрашиваемые ПС в виде утверждений ресурсы пользователя (см. Г.4.1).

Вместо "определяюn" следует писать "определяют". 

11. Приложение Г.2.12
> Вторая (правая) половина хэ-значения должна отбрасываться.

Вместо "хэ-значения" следует писать "хэш-значения". 

12. Приложение Г.3.3
> Фамилия может отсуствовать.

Вместо "отсуствовать" следует писать "отсутствовать". 

13. Приложение Г.3.6
> Утверждение preferred_username содержит сокращенное имя пользователя, которое пользователь препочитает использовать при взаимодействии с ПС.

Вместо "препочитает" следует писать "предпочитает". 

14. Приложение Г.3.17
> Для того, чтобы проверка была завершена успешно, номер phone_number, включая возможное расширение, должен соответствовать форматам, определенному в [5, 24].

Согласно [правилу](https://russkiiyazyk.ru/punktuatsiya/dlia-togo-chtoby-zapyataya.html) вместо "Для того, чтобы" следует писать "Для того чтобы". 

15. Приложение Е.2
> Проерить, что идентификатор СИ как издателя БА совпадает с идентификатором, указанным в утверждении iss.

Вместо "Проерить" следует писать "Проверить". 

16. Приложение Е.2
> Допустимое превышение времени может являться специфическим для каждой ПС и определяется с учетом времени хранения на ПС синхропосылок запроса авторищации / аутентификации.

Вместо "авторищации" следует писать "авторизации". 

17. Приложение Е.2
> Проверить наличие в БА утверждения nonce: оно должно присуствовать, если билет возвращен с узла Authorization или если билет возвращен с узла Token и запрос авторизации / аутентификации включал параметр nonce.

Вместо "присуствовать" следует писать "присутствовать".

**Comment by agievich** [comment]
Опечатки устранены в https://github.com/bcrypto/bias/commit/f293454d0f2c036ad29a6f7c02a0b905d4f9b7af.

Вместо "в Интернет" теперь "в Интернете". Предложенный вариант "в сети Интернет" будет обсужден при нормоконтроле.
