### ISSUE TITLE
Уточнить требования к защите соединений

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#13]
Структурный элемент стандарта: весь стандарт

В тексте Стандарта встречается фраза «… соединение должно быть защищено …», но при этом не выдвигаются требования к организации защиты. Из-за этого неясно, можно ли считать защищенным, например, GSM-соединение, в котором шифрование выполняется по алгоритму из семейства A5? 

Предлагается явно указать требуемые уровни стойкости криптографических алгоритмов, использующихся для организации защищенного соединения, а также порекомендовать использование криптографических алгоритмов из серии СТБ 34.101 для организации защиты в тех случаях, когда отсутствуют технические ограничения, затрудняющие их применение.

**Comment by agievich** [comment]
Предлагается уточнить требование ВТ.9:

> **Требование ВТ.9 (1-3)**. Сетевой токен должен взаимодействовать со СИ по дополнительному соединению, отличному от основного соединения КП -- СИ. Аутентификатор, который СИ передает сетевому токену по дополнительному соединению, должен быть зашифрован. Перед отправкой аутентификатора сетевой токен должен быть аутентифицирован перед СИ. Для шифрования и аутентификации должны использоваться либо СКЗИ, удовлетворяющие требованиям СТБ 34.101.27, либо стандартные криптографические механизмы сетей мобильной связи.

**Comment by agievich** [comment]
Дополнительно везде по тексту произведены замены:
- "сеть мобильной связи" -> "сеть сотовой связи";
- "мобильный телефон" -> "сотовый телефон".

Изменения приближают к терминологии СТБ 2004-2012 "Сеть сотовой подвижной электросвязи. Термины и определения".
