### ISSUE TITLE
Доработать рисунок со схемой взаимодействия сторон инфрастуктуры

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#15]
Структурный элемент стандарта: раздел 4, п. 4.6

На рисунке 1 отсутствует поясняющая надпись на пунктирной стрелке между СИ и СР. Из-за этого не совсем ясно, какие именно данные передаются от СР к СИ. 

Предлагается явно указать назначение данной стрелки.

**Comment by agievich** [comment]
Рисунок изменен: 
- стрелка, связывающая СИ с СР сделано однонаправленной;
- добавлена надпись "ресурсы пользователя" (с номером 3);
- изменены номера других надписей.

**Comment by agievich** [comment]
Реализовано в https://github.com/bcrypto/bias/commit/88c0d88b3768e1fec69d9afcbe83854479480bf3.
