### ISSUE TITLE
Виртуальная регистрация на уровне 1

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#16]
Структурный элемент стандарта: раздел 5, п. 5.1.2

Требования РП.4 и РП.5 устанавливают правила виртуальной регистрации на уровнях гарантий 1 и 2. Вместе с тем согласно таблице 1 (раздел 4, п. 4.3) виртуальная регистрации описана только для уровня гарантий 2. 

Предлагается уточнить вопрос о возможности и целесообразности использования виртуальной регистрации на уровне гарантий 1.

**Comment by agievich** [comment]
На уровне 1 вместо удаленной регистрации можно использовать виртуальную, повышая тем самым гарантии безопасности. Добавлено требование РП.1 (со сдвигом номеров остальных требований), где об этом говорится явно:
> **Требование РП.1 (1)**.  Должна проводиться удаленная или виртуальная регистрация пользователей.

Реализовано в https://github.com/bcrypto/bias/commit/9768df8f7ee925061c66bfea76b54b6531837ea7.
