### ISSUE TITLE
Дополнение правил сбора идентификационных данных в требовании РП.7

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#18]
Структурный элемент стандарта: раздел 5, п. 5.1.2

В Примечании 2 к требованию РП.7 устанавливаются правила сбора идентификационных данных. При этом не учтена статья 4 (пункт 3) Закона Республики Беларусь «О защите персональных данных», согласно которой «Обработка персональных данных осуществляется с согласия субъекта персональных данных …». 

Предлагается добавить дополнительное правило: «получить от пользователя явное согласие на сбор и обработку персональных данных».

**Comment by agievich** [comment]
В требование добавлена фраза:
> Должно быть получено явное согласие пользователя на сбор данных.

Реализовано в https://github.com/bcrypto/bias/commit/cd8294f679a988f4da7f50c3af3859613f9b1008.
