### ISSUE TITLE
Уточнить классифицирующие признаки слабых и адекватных удостоверений

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#20]
Структурный элемент стандарта: раздел 5, п. 5.2.1

В 6 абзаце приведены примеры удостоверений, отнесенных к классу «адекватных». При этом неясно, почему в состав примеров были включены свидетельство о рождении и кредитная карта. 

Так, свидетельство о рождении выдается без подтверждения личности владельца и не обладает какими-либо преимуществами, которые делают его более надежным удостоверением, чем диплом об образовании (оба документа имеют уникальный номер, ФИО владельца и физические элементы защиты). 

Кредитная карта зачастую является неименной, а с учетом устоявшейся практики по отправке банками карт по почте, нельзя гарантировать «высокую достоверность принадлежности предъявителю». 

Предлагается либо перенести данные примеры в класс «слабых удостоверений», а в класс «адекватных удостоверений» включить студенческий билет, либо уточнить правила, по которым осуществляется классификация слабых и адекватных удостоверений.

**Comment by agievich** [comment]
Свидетельство о рождении и кредитная карта перенесены в разряд слабых удостоверений, студенческий билет добавлен в разряд адекватных.
