### ISSUE TITLE
Редакторская правка описания сильного удостоверения

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#21]
Структурный элемент стандарта: раздел 5, п. 5.2.1

В 7 абзаце предложение «Удостоверение обязательно содержит и номер, и фотографию, а возможно и другие биометрические данные владельца.» предлагается изменить на «Удостоверение обязательно содержит и номер, и биометрические данные владельца (по крайней мере, фотографию владельца).»

**Comment by agievich** [comment]
Фотография, вообще говоря, не относится к биометрическим данным (не поддерживается "автоматическое распознавание", см. обсуждение в #14).

Предлагается скорректировать описания адекватного и сильного удостоверений, исключив в фразах "фотография и другие биометрические данные" слово "другие":

> **Адекватное удостоверение**... Удостоверение содержит либо номер, который однозначно указывает на владельца, либо фотографию, либо биометрические данные владельца.

> **Сильное удостоверение**... Удостоверение обязательно содержит и номер, и фотографию, а возможно и биометрические данные владельца.
