### ISSUE TITLE
Усиление требований к виртуальной регистрации на уровне гарантий 2

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#22]
Структурный элемент стандарта: раздел 5, п. 5.2.2

Из совокупности требований ПЛ.2, ПЛ.4, ПЛ.6 и ПЛ.7 следует, что пользователь может произвести виртуальную регистрацию в системе с уровнем гарантий 2, предъявив 1 сильное или 2 адекватных удостоверения, которые будут проверены способом в). С учетом низкого разрешения большинства веб-камер, серьезно возрастает риск фальсификации идентификационных данных. 

Предлагается добавить в текст Стандарта требование проводить обязательную проверку предъявляемых пользователем удостоверений способом а), если проводится виртуальная регистрация на уровне гарантий 2.

**Comment by agievich** [comment]
В преамбуле пакета ПЛ после описания способов проверки предлагается добавить фразу:

> При выборе способа проверки следует учитывать, что при удаленной или виртуальной регистрации применение способов б) -- г) затруднено или даже невозможно.
