### ISSUE TITLE
Опечатка в требовании ПЛ.7

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#24]
Структурный элемент стандарта: раздел 5, п. 5.2.2

Вместо «Требование ПЛ.7 (1, 2). Сильное удостоверение должно проверяться одним _из_ несколькими способами из списка а) – г).» следует писать «Требование ПЛ.7 (1, 2). Сильное удостоверение должно проверяться одним _или_ несколькими способами из списка а) – г).»

**Comment by agievich** [comment]
Опечатка устранена в https://github.com/bcrypto/bias/commit/8cda0a0371cf13749e715408b78e1f2ab146408e.
