### ISSUE TITLE
Требование ВТ.11 может быть невыполнимо?

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#25]
Структурный элемент стандарта: раздел 6, п. 6.1.2

По умолчанию требование ВТ.11 не может быть выполнено на некоторых сетевых токенах для заблокированного состояния: как минимум, смартфоны на базе ОС Android отображают содержание аутентификатора (смс-сообщения) на экране блокировки. 

Предлагается исключить данное требование.

**Comment by agievich** [comment]
Требование сохранено с ослаблением (https://github.com/bcrypto/bias/commit/438367b116c568e84dff880afd007c2c07c46eb0, https://github.com/bcrypto/bias/commit/d7b343769877154127718728ac33a277516afd72), которое реализует посыл замечания:

> **Требование ВТ.11 (1 – 3)**. Владелец сетевого токена должен быть проинструктирован о необходимости настройки токена так, чтобы в неактивном (заблокированном) состоянии токен не отображал аутентификаторы.

> **Примечание** — Если в качестве токена выступает смартфон, то его настройка может состоять в подавлении отображения сообщений с аутентификаторами на экране блокировки. При этом уведомления о приеме сообщений можно не блокировать.
