### ISSUE TITLE
Необъявленные типы токенов в требовании ВТ.20

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#28]
Структурный элемент стандарта: раздел 6, п. 6.1.2

В требовании ВТ.20 используется типы ТА «однофакторный КТ» и «аппаратный OTP-токен», которые отсутствуют в обзоре пакета ВТ.

Предлагается либо уточнить список токенов в обзоре пакета, либо изменить названия токенов в требовании ВТ.20.

**Comment by agievich** [comment]
В требовании ВТ.20 фраза «однофакторный КТ» изменена на «однофакторный аппаратный КТ», вместо «аппаратный ОТР-токен» теперь «аппаратный ОТР-токен (однофакторный или многофакторный)».

Реализовано в https://github.com/bcrypto/bias/commit/3cb8ec8386c3adba5946f8a474fe5a69bdc8bd79.
