### ISSUE TITLE
Уточнить требования к СКЗИ в требовании УА.4

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#34]
Структурный элемент стандарта: раздел 6, п. 6.2.2

В требовании УА.4 есть следующее предложение: «Шифрование на мастер-ключе выполняется с помощью СКЗИ, удовлетворяющего требованиям СТБ 34.101.27.». Из требования ЗО.1 (СТБ 34.101.27) следует, что на 1 уровне СКЗИ защита долговременных критических объектов может осуществляться с помощью системных методов, что в данном случае неприемлемо. 

Поэтому  предлагается заменить данное предложение на следующее: «Шифрование на мастер-ключе выполняется с помощью СКЗИ, удовлетворяющего требованиям СТБ 34.101.27 (уровни 2-4).».

**Comment by agievich** [comment]
Предложение принято: СКЗИ уровня 1 заблокированы.
