### ISSUE TITLE
Уточнить процедуру повторной аутентификации

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#36]
Структурный элемент стандарта: раздел 7, п. 7.3.1

В 7 абзаце в предложении «Например, ПС снова готовит запрос аутентификации, КП переадресует билет СИ, КП и СИ выполняют протокол аутентификации, СИ выпускает БА, ПС на основании БА выпускает новый БС.» предлагается уточнить, какой именно билет КП переадресует СИ.

**Comment by agievich** [comment]
Абзац переписан (с учетом исключения требования УС.9, см. #38):
> Для продолжения сеанса проводится повторная аутентификация. Она может быть проще первоначальной (см. требование ВТ.19), может выполняться по другой схеме, например с использованием выпущенного ранее БА.

Реализовано в https://github.com/bcrypto/bias/commit/d8821ecaf824f8a3a2d4f2e004cb0dd185cb2d79.
