### ISSUE TITLE
Уточнить требования к ГСЧ в требовании УС.1

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#37]
Структурный элемент стандарта: раздел 7, п. 7.3.2

В требовании УС.1 используется размытая формулировка «… должен использоваться надежный генератор случайных чисел». 

Предлагается писать «… должен использоваться надежный генератор случайных чисел, который удовлетворяет требованиям СТБ 34.101.27 (пункт 5.10)».

**Comment by agievich** [comment]
Фраза "Для построения БС должен использоваться надежный генератор случайных чисел" исключена (https://github.com/bcrypto/bias/commit/31b044e4fc75adee86a1ada8955c5769a379ae30). Это повышает единообразие: при генерации других объектов предъявляются требования по энтропии и не предъявляются требования к используемым генераторам. Требование по энтропии БС предъявлено -- это требование УС.3.
