### ISSUE TITLE
Уточнить требование УС.9

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#38]
Структурный элемент стандарта: раздел 7, п. 7.3.2

В требовании УС.9 предлагается уточнить фразу «… КП должна предъявлять СИ билет их сеанса», так как неясно, про какой именно билет идет речь: выпущенный ПС или выпущенный СИ.

**Comment by agievich** [comment]
Требование УС.9 исключено (https://github.com/bcrypto/bias/commit/99ac51a5ebb77388ba7dd18de5bd7da291587ac1): оно навязывает неправомерно жесткую схему повторной аутентификации.
