### ISSUE TITLE
Замена слова "прогон" на литературный синоним

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#39]
Структурный элемент стандарта: раздел 8, п. 8.2

В 1 и 3 абзаце данного пункта по одному  разу используется слово «прогон», которое в данном контексте скорее всего является жаргонным. 

Поэтому предлагается заменить его на какой-либо литературный синоним, например «запуск» или «проведение».

**Comment by agievich** [comment]
Считаем приемлемым использовать термин «прогон» применительно к протоколу или, как в данном случае, коммуникационной схеме. Например, термин «прогон» был использован нами в СТБ 34.101.66 (см. определение термина «сеанс протокола»). Тем не менее, чтобы снизить риск неверных интерпретаций, фраза «без повторного прогона схемы» уточнена до «без повторного прогона схемы Code», а фраза «Перед прогоном схемы» изменена на «Перед взаимодействием по схеме Code».

Реализовано в https://github.com/bcrypto/bias/commit/cd5244142ddd7450c01619d4c750299ba4c99359.
