### ISSUE TITLE
Уточнить таблицу "Выбор коммуникационной схемы"

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#40]
Структурный элемент стандарта: раздел 8, п. 8.5

В таблице 6 указаны 2 возможных значения параметра `response_type` для схемы `Implicit` и 3 возможных значения параметра `response_type` для схемы `Hybrid`. При этом неясно, в чем заключаются отличия между разными параметрами для одной схемы. 

Предлагается уточнить отличия в дополнительном столбце таблицы.

**Comment by agievich** [comment]
Семантика параметра `response_type` пояснена (https://github.com/bcrypto/bias/commit/413f5672eec6e53b58fba528141f8fe507fc22ae):
> В лексемах параметра перечисляются ожидаемые в ответе с узла Authorization билеты: `"code"` указывает на код авторизации, `"id_token"` –  на БА, `"token"` – на БД.
