### ISSUE TITLE
Добавить упоминание СТБ 34.101.31 в пункт Д.2

### ISSUE THREAD

**Issue by mkazl** [bcrypto/bias#41]
Структурный элемент стандарта: приложение Д, п. Д.2

В 3 абзаце упоминается алгоритм `bign-with-hbelt`, однако далее по тексту отсутствует ссылка  на СТБ 34.101.31, в котором определена использующаяся в данной алгоритме функция хэширования. 

Поэтому предлагается предложение «Алгоритм и параметры определены в СТБ 34.101.45, СТБ 34.101.77.» заменить на «Алгоритмы и параметры определены в СТБ 34.101.31, СТБ 34.101.45, СТБ 34.101.77.»

**Comment by agievich** [comment]
Алгоритм `bign-with-hbelt` определен в СТБ 34.101.45 через ссылку на СТБ 34.101.31. Двойная ссылка на СТБ 34.101.31 представляется нецелесообразной.

Тем не менее, начало обсуждаемой фразы изменено в https://github.com/bcrypto/bias/commit/56f42621724484fd5779e831dcb625412c19772a: «Алгоритмы и параметры» вместо «Алгоритм и параметры».
